<?xml version="1.0" encoding="utf-8"?><Database Name="Food1" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-7NBJA4E\SQLEXPRESS;Initial Catalog=Food1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Food1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TA1" Member="TA1s">
    <Type Name="TA1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>